import { ClientFormProvider } from "@/provider/FormProvider";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <ClientFormProvider>{children}</ClientFormProvider>
      </body>
    </html>
  );
}
